SELECT i.REST_ID,i.REST_NAME,i.FOOD_TYPE,i.FAVORITES,i.ADDRESS,round(AVG(r.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS i join REST_REVIEW AS r
ON i.REST_ID=r.REST_ID
GROUP BY i.REST_ID
HAVING i.ADDRESS LIKE "서울%"
ORDER BY SCORE desc,i.FAVORITES desc;